# Generated by Django 3.2.8 on 2022-02-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='header',
            new_name='header_img',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='profile',
            new_name='profile_img',
        ),
    ]
