# Generated by Django 3.2.8 on 2022-01-07 09:45

from django.db import migrations, models
import tasks_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='header',
            field=models.ImageField(default='header.jpg', upload_to=tasks_api.utils.upload_file),
        ),
        migrations.AddField(
            model_name='setting',
            name='profile',
            field=models.ImageField(default='profile.jpg', upload_to=tasks_api.utils.upload_file),
        ),
    ]
