# Generated by Django 3.2.8 on 2021-11-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0002_alter_project_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inviteLink',
            field=models.SlugField(blank=True),
        ),
    ]
