# Generated by Django 3.2.8 on 2021-11-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0004_rename_invitelink_project_inviteslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='users',
        ),
    ]
