# Generated by Django 3.2.8 on 2021-11-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0005_rename_user_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tasks_api.project'),
        ),
    ]
