# Generated by Django 3.2.8 on 2021-11-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_api', '0011_alter_comment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.AddField(
            model_name='activity',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tasks_api.project'),
        ),
    ]
