# Generated by Django 3.2.8 on 2021-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0012_auto_20211103_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
