# Generated by Django 3.2.8 on 2021-11-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0013_auto_20211103_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
