# Generated by Django 3.2.8 on 2021-11-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0015_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completedDate',
        ),
    ]
