# Generated by Django 3.2.8 on 2021-11-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0016_auto_20211103_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
