# Generated by Django 3.2.8 on 2021-11-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0017_section_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='every',
            field=models.CharField(blank=True, choices=[('0', 'EveryDay'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=1, null=True),
        ),
    ]
