# Generated by Django 3.2.8 on 2021-10-29 09:38

from django.db import migrations, models
import tasks.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211029_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.utils.upload_file),
        ),
    ]
