# Generated by Django 3.2.8 on 2022-10-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_project_inbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='inviteSlug',
            new_name='invite_slug',
        ),
    ]
