# Generated by Django 3.2.8 on 2022-10-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        ('label', '0001_initial'),
        ('task', '0004_rename_inviteslug_project_invite_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='label',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='label',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='label.Label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='section.section'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
