# Generated by Django 3.2.8 on 2022-10-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20220207_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('invite_slug', models.SlugField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('inbox', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='project.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8']], max_length=1, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to=task.utils.upload_file)),
                ('label', models.ManyToManyField(blank=True, related_name='projects', to='label.Label')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='project.project')),
            ],
            options={
                'unique_together': {('owner', 'project'), ('owner', 'position')},
            },
        ),
    ]
