# Generated by Django 3.2.8 on 2022-10-29 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together={('owner', 'project')},
        ),
    ]
